export const navItems = [
  {
    id: 'home',
    name: "Home",
    icon_dark: "/assets/icons/home-not_selected.svg",
    icon_light: "/assets/icons/home-selected.svg",
    url: "/dashboard",
  },
  {
    id: 'PdfNotes',
    name: "My PDF",
    icon_dark: "/assets/icons/my_pdf-not_selected.svg",
    icon_light: "/assets/icons/my_pdf-selected.svg",
    url: "/dashboard/pdf",
    hasDropdown: true,
    type: "pdf",
  },
  {
    id: 'notes',
    name: "My Notes",
    icon_dark: "/assets/icons/my_notes-not_selected.svg",
    icon_light: "/assets/icons/my_notes-selected.svg",
    url: "/dashboard/notes",
    hasDropdown: true,
    type: "note",
  },
  // {
  //   id: 'community',
  //   name: "Community",
  //   icon: "/assets/icons/video.svg",
  //   url: "/dashboard/community",
  // },
  {
    id: 'chat',
    name: "Acolyte",
    icon_dark: "/assets/icons/acolyte-not_selected.svg",
    icon_light: "/assets/icons/acolyte-selected.svg",
    url: "/workspace/chat/null",
  },
];

export const actionsDropdownItems = [
  {
    label: "Rename",
    icon: "/assets/icons/edit.svg",
    value: "rename",
  },
  {
    label: "Details",
    icon: "/assets/icons/info.svg",
    value: "details",
  },
  {
    label: "Share",
    icon: "/assets/icons/share.svg",
    value: "share",
  },
  {
    label: "Download",
    icon: "/assets/icons/download.svg",
    value: "download",
  },
  {
    label: "Delete",
    icon: "/assets/icons/delete.svg",
    value: "delete",
  },
];

export const sortTypes = [
  {
    label: "Date created (newest)",
    value: "$createdAt-desc",
  },
  {
    label: "Created Date (oldest)",
    value: "$createdAt-asc",
  },
  {
    label: "Name (A-Z)",
    value: "name-asc",
  },
  {
    label: "Name (Z-A)",
    value: "name-desc",
  },
  {
    label: "Size (Highest)",
    value: "size-desc",
  },
  {
    label: "Size (Lowest)",
    value: "size-asc",
  },
];

export const avatarPlaceholderUrl =
  "https://img.freepik.com/free-psd/3d-illustration-person-with-sunglasses_23-2149436188.jpg";

export const MAX_FILE_SIZE = 50 * 1024 * 1024; // 50MB


// Convert subject options to the format required by MultiSelector
export const subjectOptions = [
  { value: "anatomy", label: "Anatomy" },
  { value: "physiology", label: "Physiology" },
  { value: "biochemistry", label: "Biochemistry" },
  { value: "pathology", label: "Pathology" },
  { value: "pharmacology", label: "Pharmacology" },
  { value: "microbiology", label: "Microbiology" },
  { value: "forensic_medicine", label: "Forensic Medicine" },
  { value: "community_medicine", label: "Community Medicine (Preventive and Social Medicine)" },
  { value: "ophthalmology", label: "Ophthalmology" },
  { value: "ent", label: "Otorhinolaryngology (ENT)" },
  { value: "general_medicine", label: "General Medicine" },
  { value: "general_surgery", label: "General Surgery" },
  { value: "pediatrics", label: "Pediatrics" },
  { value: "obgyn", label: "Obstetrics and Gynecology" },
  { value: "orthopaedics", label: "Orthopaedics" }
];

// Combined exam options in a single list
export const examOptions = [
  { value: "NEET-PG", label: "NEET PG", description: "MD/MS/PG Diploma/DNB post-MBBS" },
  { value: "NEET-MDS", label: "NEET MDS", description: "MDS/PG Diploma (Dental)" },
  { value: "AIAPGET", label: "AIAPGET", description: "MD, MS, PG Diploma (AYUSH courses)" },
  { value: "FMGE", label: "FMGE", description: "Licensing Examination" },
  { value: "DNB-PDCET", label: "DNB PDCET", description: "DNB" },
  { value: "NEET-SS", label: "NEET SS", description: "DM, MCh" },
  { value: "FET", label: "FET", description: "FNB" },
  { value: "INI-CET", label: "INI CET", description: "MD, MS, DM, M.Ch, MDS" },
  { value: "AIIMS-INI-SS", label: "AIIMS INI SS", description: "DM, MCh, MD(Hospital Administration)" },
  { value: "MCAT", label: "MCAT", description: "Medical College Admission Test" },
  { value: "USMLE-STEP1", label: "USMLE- STEP1", description: "United States Medical Licensing Examination Step 1" },
  { value: "USMLE-STEP2", label: "USMLE- STEP2", description: "United States Medical Licensing Examination Step 2" },
  { value: "USMLE-STEP3", label: "USMLE- STEP3", description: "United States Medical Licensing Examination Step 3" },
  { value: "OTHER", label: "Others", description: "Specify your own exam" }
];



export const colleges = [
  // "All medical colleges",
  "Viswabharathi Medical College, Kurnool",
  "Andaman & Nicobar Islands Institute of Medical Sciences, Port Blair",
  "S V Medical College, Tirupati",
  "SVIMS - Sri Padmavathi Medical College for Women, Alipiri Road, Tirupati",
  "Sri Balaji Medical College, Hospital and Research Institute, Chittoor",
  "Santhiram Medical College, Nandyal",
  "Rangaraya Medical College, Kakinada",
  "Rajiv Gandhi Institute of Medical Sciences, Srikakulam",
  "P E S Institute Of Medical Sciences and Research, Kuppam",
  "NRI Medical College, Guntur",
  "NRI Institute of Medical Sciences, Visakhapatnam",
  "Nimra Institute of Medical Sciences, Krishna Dist., A.P.",
  "Narayana Medical College, Nellore",
  "Maharajah Institute of Medical Sciences, Vizianagaram",
  "Kurnool Medical College, Kurnool",
  "Konaseema Institute of Medical Sciences & Research Foundation, Amalapuram",
  "Katuri Medical College, Guntur",
  "Guntur Medical College, Guntur",
  "GSL Medical College, Rajahmundry",
  "Great Eastern Medical School and Hospital,Srikakulam",
  "Government Siddhartha Medical College, Vijaywada",
  "Government Medical College, Vizianagaram",
  "Government Medical College, Rajamahendravaram",
  "Government Medical College, Paderu",
  "Government Medical College, Ongole (Previously known as Rajiv Gandhi Institute of Medical Sciences, Ongole,)",
  "Government Medical College, Nandyal",
  "Government Medical College, Machilipatnam",
  "Government Medical College, Kadapa",
  "Government Medical College, Eluru",
  "Government Medical College, Ananthapuram",
  "GITAM Institute of Medical Sciences and Research, Visakhapatnam",
  "Gayathri Vidya Parishad Institute of Health Care & Medical Technology, Visakhapatnam",
  "Fathima Instt. of Medical Sciences,Kadapa",
  "Dr. P.S.I. Medical College , Chinoutpalli",
  "Apollo Institute of Medical Sciences and Research, Chittoor",
  "Andhra Medical College, Visakhapatnam",
  "Alluri Sitaram Raju Academy of Medical Sciences, Eluru",
  "All India Institute of Medical Sciences, Mangalagiri, Vijayawada",
  "ACSR Government Medical College Nellore",
  "Tomo Riba Institute of Health & Medical Sciences, Naharlagun",
  "Tinsukia Medical College",
  "Tezpur Medical College & Hospital, Tezpur",
  "Silchar Medical College, Silchar",
  "Nalbari Medical College, Nalbari",
  "Nagaon Medical College",
  "Lakhimpur Medical College",
  "Kokrajhar Medical College",
  "Jorhat Medical College & Hospital , Jorhat",
  "Gauhati Medical College, Guwahati",
  "Fakhruddin Ali Ahmed Medical College, Barpeta, Assam",
  "Diphu Medical College & Hospital, Diphu, Assam",
  "Dhubri Medical College, Dhubri",
  "Assam Medial College, Dibrugarh",
  "All India Institute of Medical Sciences, Guwahati",
  "Shri Krishna Medical College, Muzzafarpur",
  "Shree Narayan Medical Institute and Hospital",
  "Radha Devi Jageshwari Memorial Medical College and Hospital",
  "Patna Medical College, Patna",
  "Netaji Subhas Medical College & Hospital, Amhara, Bihta, Patna",
  "Narayan Medical College & Hospital, Sasaram",
  "Nalanda Medical College, Patna",
  "Mata Gujri Memorial Medical College, Kishanganj",
  "Madhubani Medical College, Madhubani",
  "Lord Buddha Koshi Medical College and Hospital, Saharsa",
  "Katihar Medical College, Katihar",
  "Jawaharlal Nehru Medical College, Bhagalpur",
  "Jannayak Karpoori Thakur Medical College & Hospital, Madhepura, Bihar",
  "Indira Gandhi Institute of Medical Sciences,Sheikhpura, Patna",
  "Himalaya Medical College and Hospital, Patna",
  "Government Medical College, Purnea",
  "Government Medical College, Bettiah",
  "Employees State Insurance Corporation Medical College,Patna",
  "Darbhanga Medical College, Lehriasarai",
  "Bhagwan Mahavir Institute of Medical Sciences, Pawapuri (Formely known as Vardhman Institute of Medical Sciences, Pawapuri)",
  "Anugrah Narayan Magadh Medical College, Gaya",
  "All India Institute of Medical Sciences, Patna",
  "Government Medical College, Chandigarh",
  "Shri Shankaracharya Institute of Medical Sciences, Bhilai",
  "Shri Rawatpura Sarkar Institute of Medical Sciences and Research",
  "Shri Balaji Institute of Medical Science",
  "Rajmata Shrimati Devendra kumari Singhdeo Government Medical College, Surguja ( C.G.)",
  "Raipur Institute of Medical Sciences (RIMS), Raipur",
  "Pt. J N M Medical College, Raipur",
  "Late Shri Lakhi Ram Agrawal Memorial Govt. Medical College, Raigarh",
  "Late Shri Baliram Kashyap Memorial NDMC Govt. Medical College, Jagdalpur",
  "Government Medical College, Mahasamund",
  "Government Medical College, Korba",
  "Government Medical College, Kanker",
  "Government Medical College (Bharat Ratna Shri Atal Bihari Vajpyee Memorial Med. Col.), Rajnandgaon",
  "Chhattisgarh Institute of Medical Sciences, Bilaspur",
  "Chandulal Chandrakar Memorial Govt. Medical College, Durg",
  "All India Institute of Medical Sciences, Raipur",
  "Abhishek I Mishra Memorial Medical College & Research, Bhiali",
  "NAMO Medical Education and Research Institute, Silvassa",
  "Vardhman Mahavir Medical College & Safdarjung Hospital, Delhi",
  "University College of Medical Sciences & GTB Hospital, New Delhi",
  "North Delhi Muncipal Corporation Medical College, Delhi",
  "Maulana Azad Medical College, New Delhi",
  "Lady Hardinge Medical College, New Delhi",
  "Hamdard Institute of Medical Sciences & Research, New Delhi",
  "Dr. Baba Saheb Ambedkar Medical College, Rohini, Delhi",
  "Atal Bihari Vajpayee Institute of Medical Sciences and Dr. RML Hospital, New Delhi",
  "Army College of Medical Sciences, New Delhi",
  "All India Institute of Medical Sciences, New Delhi",
  "Goa Medical College, Panaji",
  "Zydus Medical College & Hospital, Dahod",
  "Swaminayaran Institute of Medical Sciences & Research",
  "Surat Municipal Institute of Medical Education & Research, Surat",
  "Smt. N.H.L.Municipal Medical College, Ahmedabad",
  "Shantabaa Medical College, Amreli",
  "SBKS Medical Instt. & Research Centre, Vadodra",
  "SAL Institute of Medical Sciences, Ahmedabad",
  "Pramukhswami Medical College, Karmsad",
  "Parul Institute of Medical Sciences & Research, Vadodara",
  "Pandit Deendayal Upadhyay Medical College, Rajkot",
  "Nootan Medical College and Research Centre, Mehsana",
  "Narendra Modi Medical College, Ahmedabad (Formely known as Ahmedabad Muncipal Coporation Medical Edu. Trust Medical College)",
  "MP Shah Medical College,Jamnagar",
  "Medical College, Baroda",
  "Kiran Medical College, Surat",
  "Gujarat Adani Institute of Medical Sciences, Bhuj",
  "Government Medical College, Surat",
  "Government Medical College, Porbandar",
  "Government Medical College, Panchmahal Godhra",
  "Government Medical College, Morbi",
  "Government Medical College, Bhavnagar",
  "GMERS Medical College, Valsad",
  "GMERS Medical College, Vadnagar, Mehsana",
  "GMERS Medical College, Sola, Ahmedabad",
  "GMERS Medical College, Rajpipla",
  "GMERS Medical College, Navsari",
  "GMERS Medical College, Junagadh",
  "GMERS Medical College, Hadiyol, Himmatnagar",
  "GMERS Medical College, Gotri, Vadodara",
  "GMERS Medical College, Gandhinagar",
  "GMERS Medical College, Dharpur Patan",
  "GCS Medical College, Ahmedabad",
  "Dr. N.D. Desai Faculty of Medical Science and Research, Nadiad",
  "Dr. M.K. Shah Medical College & Research Centre, Ahmedabad",
  "Dr.Kiran C.Patel Medical College and Research Institute",
  "CU Shah Medical College, Surendra Nagar",
  "B J Medical College, Ahmedabad",
  "Bhagyoday Medical College",
  "Banas Medical College and Research Institute, Palanpur, Gujarat",
  "Ananya College of Medicine & Research",
  "All India Institute of Medical Sciences, Rajkot",
  "World College of Medical Sciences & Researc, Jhajjar, Haryana",
  "Shri Atal Bihari Vajpayee Government Medical College, Faridabad",
  "Shaheed Hasan Khan Mewati Government Medical College, Nalhar",
  "Pt. B D Sharma Postgraduate Institute of Medical Sciences, Rohtak (Haryana)",
  "N.C. Medical College & Hospital, Panipat",
  "Maharishi Markandeshwar Institute Of Medical Sciences & Research, Mullana, Ambala",
  "Maharishi Markandeshwar College of Medical Sciences & Research, Sadopur",
  "Maharaja Agrasen Medical College, Agroha",
  "Kalpana Chawala Govt. Medical College, Karnal, Haryana",
  "Faculty of Medicine and Health Sciences, Gurgaon (Formarly SGGST Medical College & R Centre,Gurgaon)",
  "Employees State Insurance Corporation Medical College, Faridabad",
  "BPS Government Medical College for Women, Sonepat",
  "Amrita School of Medicine, Faridabad",
  "Al Falah School of Medical Sciences & Research Centre, Faridabad",
  "Adesh Medical College and Hospital, Shahabad, Kurukshetra, Haryana",
  "Shri Lal Bahadur Shastri Government Medical College, Mandi, HP",
  "Pt. Jawahar Lal Nehru Government Medical College, Chamba",
  "Maharishi Markandeshwar Medical College & Hospital, Solan",
  "Indira Gandhi Medical College, Shimla",
  "Government Medical College, Nahan, Sirmour H.P.",
  "Dr. Rajendar Prasad Government Medical College, Tanda, H.P",
  "Dr. Radhakrishnan Government Medical College, Hamirpur, H.P",
  "All India Institute of Medical Sciences, Bilaspur",
  "Sher-I-Kashmir Instt. Of Medical Sciences, Srinagar",
  "Govt. Medical College, Doda, Kashmir",
  "Government Medical College, Udhampur",
  "Government Medical College, Srinagar",
  "Government Medical College, Rajouri, J&K",
  "Government Medical College, Kathua",
  "Government Medical College, Jammu",
  "Government Medical College, Handwara",
  "Government Medical College, Baramulla",
  "Government Medical College, Anantnag",
  "All India Institute of Medical Sciences, Vijaypur",
  "Acharya Shri Chander College of Medical Sciences, Jammu",
  "Shahed Nirmal Mahto Medical College & Hospital, Dhanbad",
  "Rajendra Institute of Medical Sciences, Ranchi",
  "Palamu Medical College, Palamu",
  "M G M Medical College, Jamshedpur",
  "Manipal Tata Medical College,Baridih Jameshedpur",
  "Laxmi Chandravansi Medical College & Hospital",
  "Hazaribagh Medical College, Hazaribagh",
  "Dumka Medical College, Dighi Dumka",
  "All India Institute of Medical Sciences, Deoghar",
  "Yenepoya Medical College, Mangalore",
  "Yadgiri Institute of Medical Sciences, Yadgiri",
  "Vydehi Institute Of Medical Sciences & Research Centre, Bangalore",
  "Vijaynagar Institute of Medical Sciences, Bellary",
  "The Oxford Medical College, Hospital & Research Centre, Bangalore",
  "Subbaiah Institute of Medical Sciences, Shimoga, Karnataka",
  "St. Johns Medical College, Bangalore",
  "S S Institute of Medical Sciences& Research Centre, Davangere",
  "SR Patil Medical College and Hospital",
  "Sri Siddhartha Medical College, Tumkur",
  "Sri siddhartha Institute of Medical Sciences & Research Centre, Bangalore",
  "Srinivas Institute of Medical Research Centre, Srinivasnagar, mangalore",
  "Sri Madhusudan Sai Institute of Medical Sciences and Research",
  "Sri Devaraj URS Medical College, Kolar",
  "Sri Chamundeshwari Medical College Hospital & Research Institute",
  "S. Nijalingappa Medical College & HSK Hospital & Research Centre, Bagalkot",
  "Siddaganga Medical College and Research Institute, Tumakuru",
  "Shridevi Institute of Medical Sciences & Research Hospital, Tumkur",
  "Shri B M Patil Medical College, Hospital & Research Centre, Vijayapura(Bijapur",
  "Shri Atal Bihari Vajpayee Medical College & Research Institute",
  "Shimoga Institute of Medical Sciences,Shimoga",
  "SDM College of Medical Sciences & Hospital, Sattur, Dharwad",
  "Sapthagiri Institute of Medical Sciences & Research Centre, Bangalore",
  "Sambharam Institute of Medical Sciences & Research, Kolar",
  "Rajarajeswari Medical College & Hospital, Bangalore",
  "Raichur Institute of Medical Sciences,Raichur",
  "PES University Institute of Medical Sciences and Reseach Bangalore",
  "Navodaya Medical College, Raichur",
  "Mysore Medical College and Research Instt. (Prev.name Government Medical College), Mysore",
  "MVJ Medical College and Research Hospital, Bangalore",
  "M S Ramaiah Medical College, Bangalore",
  "Mandya Institute of Medical Sciences, Mandya",
  "Mahadevappa Rampure Medical College, Kalaburagi, Gulbarga",
  "K V G Medical College, Sullia",
  "K S Hegde Medical Academy, Mangalore",
  "Koppal Institute of Medical Sciences, Koppal",
  "Kodagu Institute of Medical Sciences, Kodagu",
  "Khaja Bandanawaz University - Faculty of Medical Sciences, Gulbarga",
  "Kempegowda Institute of Medical Sciences, Bangalore",
  "Kasturba Medical College, Manipal",
  "Kasturba Medical College, Mangalore",
  "Karwar Institute of Medical Sciences, Karwar",
  "Karnataka Institute of Medical Sciences, Hubballi",
  "Kanachur Institute of Medical Sciences, Mangalore",
  "JSS Medical College, Mysore",
  "JJM Medical College, Davangere",
  "Jawaharlal Nehru Medical College, Belgaum",
  "Jagadguru Gangadhar Mahaswamigalu Moorusavirmath Medical College JGMMMC",
  "Haveri Institute of Medical Sciences, Haveri",
  "Hassan Institute of Medical Sciences, Hassan",
  "Gulbarga Institute of Medical Sciences, Gulbarga",
  "G R Medical College Hospital & Research Centre",
  "Gadag Institute of Medical Sciences, Mallasamudra, Mulgund Road, Gadag",
  "Father Mullers Medical College, Mangalore",
  "Employees State Insurance Corporation Medical College, Gulbarga",
  "Employees State Insurance Corporation Medical College, Bangalore",
  "East Point College of Medical Sciences & Research Centre, Bangalore",
  "Dr. Chandramma Dayananda Sagar Instt. of Medical Education & Research, Harohalli, Hubli",
  "Dr BR Ambedkar Medical College, Bangalore",
  "Chitradurga Medical College and Research Institute",
  "Chikkamagaluru Institute of Medical Sciences, Chikkamagaluru",
  "Chikkaballapura Institute of Medical Sciences",
  "Chamrajanagar Institute of Medical Sciences, Karnataka",
  "Bidar Institute of Medical Sciences,Bidar",
  "BGS Medical College and Hospital",
  "BGS Global Institute of Medical Sciences, Bangalore",
  "Belagavi Institute of Medical Sciences, Belagavi",
  "Basaveswara Medical College and Hospital, Chitradurga",
  "Bangalore Medical College and Research Institute, Bangalore",
  "Al-Ameen Medical College,Bijapur",
  "Akash Institute of Medical Sciences & Research Centre, Devanhalli, Bangalore, Karnataka",
  "A J Institute of Medical Sciences & Research Centre, Mangalore",
  "Adichunchanagiri Institute of Medical Sciences Bellur",
  "VN Public Health and Educational Palakkad",
  "Travancore Medical College, Kollam",
  "T D Medical College, Alleppey (Allappuzha)",
  "Sree Uthradom Thiurnal Academy of Medical Sciences,Trivandrum",
  "Sree Narayana Instt. of Medical Sciences, Chalakka,Ernakulam",
  "Sree Gokulam Medical College Trust & Research Foundation, Trivandrum",
  "Pushpagiri Institute Of Medical Sciences and Research Centre, Tiruvalla",
  "P K Das Institute of Medical Sciences, Palakkad, Kerala",
  "Mount Zion Medical College, Chayalode, Ezhamkulam Adoor, Pathanamthitta",
  "M E S Medical College , Perintalmanna Malappuram Distt.Kerala",
  "Medical College, Thiruvananthapuram",
  "Malankara Orthodox Syrian Church Medical College, Kolenchery",
  "Malabar Medical College, Kozhikode,Calicut",
  "KMCT Medical College,Kozhikode, Calicut",
  "Karuna Medical College, Palakkad",
  "Kannur Medical College, Kannur",
  "Jubilee Mission Medical College & Research Institute, Thrissur",
  "Govt. Medical College,Pariyaram, Kannur (Prev. Known as Academy of Medical Sciences)",
  "Government Medical College, Thrissur",
  "Government Medical College, Parippally, Kollam",
  "Government Medical College, Manjeri, Malapuram Dist.",
  "Government Medical College, Kozhikode, Calicut",
  "Government Medical College, Kottayam",
  "Government Medical College, Konni",
  "Government Medical College (Institute of Integrated Medical Sciences), Yakkara, Palakkad",
  "Government Medical College, Idukki.",
  "Government Medical College, Ernakulam",
  "Dr. Somervel Memorial CSI Hospital & Medical College, Karakonam, Thiruvananthapuram",
  "Dr. Moopen s Medical College, Wayanad, Kerala",
  "Believers Church Medical College Hospital, Thiruvalla, Kerala",
  "Azeezia Instt of Medical Science,Meeyannoor,Kollam",
  "Amrita School of Medicine, Elamkara, Kochi",
  "Amala Institute of Medical Sciences, Thrissur",
  "Al-Azhar Medical College and Super Speciality Hospital, Thodupuzha",
  "Virendra Kumar Sakhlecha Government Medical College",
  "Sundarlal Patwa Govt. Medical College",
  "Sukh Sagar Medical College & Hospital, Jabalpur",
  "Sri Aurobindo Medical College and Post Graduate Institute , Indore",
  "Shyam Shah Medical College, Rewa",
  "School of Medical Sciences, Sri Satya Sai University of Technology and Medical Sciences",
  "Ruxmaniben Deepchand Gardi Medical College, Ujjain",
  "RKDF Medical College Hospital & Research Centre, Jatkhedi, Bhopal",
  "Ram Krishna College Hospital & Research Centre, Bhopal",
  "Peoples College of Medical Sciences & Research Centre, Bhanpur, Bhopal",
  "Netaji Subhash Chandra Bose Medical College, Jabalpur",
  "M G M Medical College, Indore",
  "Mahaveer Institute of Medical Sciences & Research, Bhopal",
  "L.N. Medical College and Research Centre,Bhopal",
  "LNCT Medical College & Sewakunj Hospital, Indore",
  "Index Medical College Hospital & Research Centre,Indore",
  "Government Medical College, Vidisha, MP",
  "Government Medical College, Shivpuri, MP",
  "Government Medical College, Shahdol, MP",
  "Government Medical College, Seoni",
  "Government Medical College, Satna",
  "Government Medical College, Ratlam",
  "Government Medical College, Khandwa, MP",
  "Government Medical College, Datia, MP",
  "Government Medical College, Chhindwara, MP",
  "Gandhi Medical College, Bhopal",
  "Gajra Raja Medical College, Gwalior",
  "Chirayu Medical College and Hospital, Bairagarh,Bhopal",
  "Bundelkhand Medical College, Sagar",
  "Amaltas Institute of Medical Sciences, Dewas",
  "All India Institute of Medical Sciences, Bhopal",
  "Vedantaa Institute of Medical Sciences, Palghar, Maharashtra",
  "Topiwala National Medical College, Mumbai",
  "Terna Medical College, Navi Mumbai",
  "Symbiosis Medical College for Women, Pune",
  "SRTR Medical College, Ambajogai",
  "Sri Bhausaheb Hire Government Medical College, Dhule",
  "Smt. Kashibai Navale Medical College and General Hospital,Pune",
  "SMBT Institute of Medical Sciences & Research Centre, Nandihills, Nashik",
  "Sindhudurg Shikshan Prasarak Mandal (SSPM) Medical College & Lifetime Hospital, Padave, Sindhudurg",
  "Shri Vasant Rao Naik Govt. Medical College, Yavatmal",
  "Shri Ramchandra Institute of Medical Sciences, Aurangabad",
  "Seth GS Medical College, and KEM Hospital, Mumbai",
  "Rural Medical College, Loni",
  "Rajiv Gandhi Medical College and Chhatrapati Shivaji Maharaj Hospital, Thane",
  "Rajashree Chatrapati Shahu Maharaj Government Medical College, Kolhapur",
  "Prakash Institute of Medical Sciences & Research, Sangli",
  "Parbhani Medical College, Parbhani",
  "Padmashree Dr. D.Y.Patil Medical College, Navi Mumbai",
  "N. K. P. Salve Instt. of Medical Sciences and Research Centre and Lata Mangeshkar Hospital, Nagpur",
  "Mahatma Gandhi Missions Medical College, Nerul, Navi Mumbai",
  "Mahatma Gandhi Missions Medical College, Navi Mumbai",
  "Mahatma Gandhi Missions Medical College, Aurangabad",
  "Mahatma Gandhi Mission Medical College, Vashi",
  "Mahatma Gandhi Institute of Medical Sciences, Sevagram, Wardha",
  "Maharashtra Institute of Medical Sciences, Latur",
  "Maharashtra Institute of Medical Education & Research, Talegaon,Pune",
  "Lokmanya Tilak Municipal Medical College, Sion, Mumbai",
  "Krishna Institute of Medical Sciences, Karad",
  "KJ Somaiyya Medical College & Research Centre, Mumbai",
  "Jawaharlal Nehru Medical College, Sawangi (Meghe), Wardha",
  "Indira Gandhi Medical College & Hospital, Nagpur",
  "Indian Institute of Medical Science & Research, Jalna",
  "H.B.T. Medical College & Dr. R.N. Cooper Municipal General Hospital, Juhu, Mumbai",
  "Grant Medical College, Mumbai",
  "Government Medical College, Washim",
  "Government Medical College, Sindhudurg",
  "Government Medical College ,Satara",
  "Government Medical College, Parbhani",
  "Government Medical College, Osmanabad",
  "Government Medical College, Nashik",
  "Government Medical College, Nandurbar",
  "Government Medical College, Nagpur",
  "Government Medical College, Mumbai",
  "Government Medical College, Miraj",
  "Government Medical College, Latur",
  "Government Medical College, Jalna",
  "Government Medical College, Jalgaon",
  "Government Medical College & Hospital, Baramati",
  "Government Medical College, Hingoli",
  "Government Medical College, Gondia",
  "Government Medical College, Gadchiroli",
  "Government Medical College, Chandrapur",
  "Government Medical College, Buldhana",
  "Government Medical College, Bhandara",
  "Government Medical College, Aurangabad",
  "Government Medical college and District Hospital, Ratnagiri",
  "Government Medical College, Amravati",
  "Government Medical College, Ambernath",
  "Government Medical College, Alibag",
  "Government Medical College, Akola",
  "Dr. Vithalrao Vikhe Patil Foundations Medical College & Hospital, Ahmednagar",
  "Dr.Vasantrao Pawar Med. Col. Hosp. & Research Centre,Nasik (Prev. NDMVP Samaj Medical College)",
  "Dr Vaishampayan Memorial Medical College, Solapur",
  "Dr. Ulhas Patil Medical College & Hospital, Jalgaon",
  "Dr. Shankarrao Chavan Govt. Medical College, Nanded",
  "Dr. Rajendra Gode Medical College, Amravati",
  "Dr. Panjabrao Alias Bhausaheb Deshmukh Memorial Medical College, Amravati",
  "Dr. N Y Tasgaonkar Institute of Medical Science",
  "Dr. D Y Patil Medical College, Kolhapur",
  "Dr. D Y Patil Medical College, Hospital and Research Centre, Pimpri, Pune",
  "Datta Meghe Medical College, Nagpur",
  "B.K.L. Walawalkar Rural Medical College, Ratnagiri",
  "B. J. Govt. Medical College, Pune",
  "Bharatratna Atal Bihari Vajpayee Medical College, Pune",
  "Bharati Vidyapeeth University Medical College, Pune",
  "Bharati Vidyapeeth Deemed University Medical College & Hospital, Sangli",
  "Ashwini Rural Medical College, Hospital & Research Centre, Solapur",
  "Armed Forces Medical College, Pune",
  "All India Institute of Medical Sciences, Nagpur",
  "ACPM Medical College, Dhule",
  "Shija Academy of Health Sciences",
  "Regional Institute of Medical Sciences, Imphal",
  "Jawaharlal Nehru Institute of Medical Sciences,Porompet,Imphal",
  "Government Medical College, Churachandpur",
  "PA Sangma International Medical College & Hospital",
  "North Eastern Indira Gandhi Regional Instt. of Health and Medical Sciences, Shillong",
  "Zoram Medical College, Mizoram",
  "Nagaland Institute of Medical Sciences & Research",
  "Veer Surendra Sai Institute of Medical Sciences and Research, Burla",
  "Sri Jagannath Medical College & Hospital, Puri",
  "SCB Medical College, Cuttack",
  "Saheed Rendo Majhi Medical College & Hospital, Bhawanipatna, Kalahandi",
  "Saheed Laxman Nayak Medical College & Hospital, Koraput",
  "Pt. Raghunath Murmu Medical College and Hospital, Baripada, Odisha",
  "MKCG Medical College, Berhampur",
  "Kalinga Institute of Medical Sciences, Bhubaneswar",
  "Instt. Of Medical Sciences & SUM Hospital, Bhubaneswar",
  "Institute of Medical Sciences & SUM Hospital",
  "Hi-Tech Medical College & Hospital, Rourkela",
  "Hi-Tech Medical College & Hospital, Bhubaneswar",
  "Government Medical College, Sundargarh",
  "Government Medical College & Hospital (Renamed as Fakir Mohan Medical College & Hospital), Balasore",
  "Government Medical College & Hospital (Renamed as Bhima Bhoi Medical College & Hospital), Balangir",
  "Government Medical College and Hospital, Jajpur",
  "DRIEMS Institute of Health Sciences and Hospital, Kairapari",
  "Dharanidhar Medical College & Hospital (DDMCH), Keonjhar,",
  "All India Institute of Medical Sciences, Bhubaneswar",
  "Vinayaka Missions Medical College, Karaikal, Pondicherry",
  "Sri Venkateswaraa Medical College, Hospital & Research Centre, Pondicherry",
  "Sri Manakula Vinayagar Medical College & Hospital, Pondicherry",
  "Sri Lakshmi Narayana Institute of Medical Sciences, Pondicherry",
  "Pondicherry Institute of Medical Sciences & Research, Pondicherry",
  "Mahatma Gandhi Medical College & Research Institute, Pondicherry",
  "Jawaharlal Institute of Postgraduate Medical Education & Research, Puducherry",
  "Indira Gandhi Medical College & Research Institute, Puducherry",
  "Aarupadai Veedu Medical College, Pondicherry",
  "Sri Guru Ram Das Institute of Medical Sciences and Research, Sri Amritsar",
  "RIMT Medical College and Hospital",
  "Punjab Institute of Medical Sciences, Jalandhar",
  "Guru Govind Singh Medical College, Faridkot",
  "Government Medical College, Patiala",
  "Government Medical College, Amritsar",
  "Gian Sagar Medical College & Hospital, Patiala",
  "Dr B R Ambedkar State Institute of Medical Sciences, SAS Nagar , Mohali",
  "Dayanand Medical College & Hospital, Ludhiana",
  "Christian Medical College, Ludhiana",
  "Chintpurni Medical College, Pathankot, Gurdaspur",
  "All India Institute of Medical Sciences, Bhatinda",
  "Adesh Institute of Medical Sciences & Research, Bhatinda",
  "Vyas Medical College & Hospital",
  "Sudha Medical College",
  "SMS Medical College, Jaipur",
  "Shri Kalyan Govt. Medical College, Sikar, Rajasthan",
  "Sardar Patel Medical College, Bikaner",
  "RUHS College of Medical Sciences, Jaipur",
  "R N T Medical College, Udaipur",
  "Pacific Medical College & Hospital, Bhilo Ka Bedla, Udaipur",
  "Pacific Institute of Medical Sciences, Umarda, Udaipur",
  "National Institute of Medical Science & Research, Jaipur",
  "Mahatma Gandhi Medical College and Hospital, Sitapur, Jaipur",
  "JIET Medical College And Hospital",
  "Jhalawar Medical College, Jhalawar",
  "Jawaharlal Nehru Medical College, Ajmer",
  "Jaipur National University Institute of Medical Sciences and Resarch Centre, Jagatpura, Jaipur",
  "Government Medical College, Sri Ganganagar",
  "Government Medical College, Sirohi",
  "Government Medical College, Sawai Madhopur",
  "Government Medical College, Pali, Rajasthan",
  "Government Medical College, Nagaur",
  "Government Medical College, Kota",
  "Government Medical College, Karauli",
  "Government Medical College, Jhunjhunu",
  "Government Medical College, Hanumangarh",
  "Government Medical College, Dungarpur",
  "Government Medical College, Dholpur",
  "Government Medical College, Dausa",
  "Government Medical College, Churu",
  "Government Medical College, Chittorgarh",
  "Government Medical College, Bundi",
  "Government Medical College, Bhilwara, Rajasthan",
  "Government Medical College, Bharatpur, Rajasthan",
  "Government Medical College, Barmer",
  "Government Medical College, Baran",
  "Government Medical College, Banswara",
  "Government Medical College, Alwar",
  "Geetanjali Medical College & Hospital,Udaipur",
  "Employees State Insurance Corporation Medical College,Alwar",
  "Dr S S Tantia Medical College Hospital & Research Centre",
  "Dr SN Medical College, Jodhpur",
  "Ananta Institute of Medical Sciences & Research Centre, Rajsamand",
  "American International Institute of Medical Sciences, Bedwas",
  "All India Institute of Medical Sciences, Jodhpur",
  "Sikkim Manipal Institute of Medical Sciences, Gangtok",
  "Vinayaka Missions Kirupananda Variyar Medical College, Salem",
  "VELS Medical College & Hospital",
  "Velammal Medical College Hospital and Research Institute, Madurai",
  "Trichy SRM Medical College Hospital & Research Centre, Trichy",
  "Tirunelveli Medical College,Tirunelveli",
  "Thoothukudi Medical College, Thoothukudi",
  "Thiruvarur Govt. Medical College, Thiruvarur",
  "Theni Government Medical College,Theni",
  "Thanjavur Medical College,Thanjavur",
  "Tagore Medical College and Hospital, Chennai",
  "Swamy Vivekanandha Medical College Hospital And Research Institute",
  "ST Peters Medical College, Hospital & Research Institute",
  "Stanley Medical College, Chennai",
  "SRM Medical College Hospital & Research Centre, Chengalpattu",
  "Sri Venkateswaraa Medical College Hospital and Research Institute, Chennai",
  "Sri Ramachandra Medical College & Research Institute, Chennai",
  "Srinivasan Medical College and Hospital",
  "Sri Muthukumaran Medical College,Chennai",
  "Sree Mookambika Institute of Medical Sciences, Kanyakumari",
  "Sree Balaji Medical College and Hospital, Chennai",
  "Shri Sathya Sai Medical College and Research Institute, Kancheepuram",
  "Saveetha Medical College and Hospital, Kanchipuram",
  "Rajah Muthiah Medical College, Annamalainagar",
  "PSP Medical College Hospital and Research Institute",
  "PSG Institute of Medical Sciences, Coimbatore",
  "Panimalar Medical College Hospital & Research Institute, Chennai,Tamil Nadu",
  "Nandha Medical College & Hospital Erode",
  "Melmaruvathur Adiparasakthi Instt. Medical Sciences and Research",
  "Meenakshi Medical College and Research Institute, Enathur",
  "Madurai Medical College, Madurai",
  "Madras Medical College, Chennai",
  "Madha Medical College and Hospital, Thandalam, Chennai",
  "KMCH Institute of Health Sciences and Research, Coimbatore",
  "Kilpauk Medical College, Chennai",
  "Karpaga Vinayaga Institute of Medical Sciences,Maduranthagam",
  "Karpagam Faculty of Medical Sciences & Research, Coimbatore",
  "K A P Viswanathan Government Medical College, Trichy",
  "Kanyakumari Medical Mission Research Centre",
  "KanyaKumari Government Medical College, Asaripallam",
  "J R Medical College and Hospital",
  "Indira Medical College & Hospitals, Thiruvallur",
  "Govt. Mohan Kumaramangalam Medical College, Salem- 30",
  "Government Villupuram Medical College, Villupuram",
  "Government Vellore Medical College, Vellore",
  "Government Thiruvannamalai Medical College, Thiruvannamalai",
  "Government Sivagangai Medical College, Sivaganga",
  "Government Medical College, Virudhunagar",
  "Government Medical College ,Tiruppur",
  "Government Medical College, Thiruvallur",
  "Government Medical College, The Nilgiris",
  "Government Medical College Ramanathapuram",
  "Government Medical College, Pudukottai, Tamil Nadu",
  "Government Medical College, Omandurar",
  "Government Medical College, Namakkal",
  "Government Medical College Nagapattinam",
  "Government Medical College Krishnagiri",
  "Government Medical College, Karur",
  "Government Medical College Kallakurichi",
  "Government Medical College & ESIC Hospital, Coimbatore, Tamil Nadu.",
  "Government Medical College,Dindigul",
  "Government Medical College,Ariyalur",
  "Government Erode Medical College & Hospital, Perundurai (Formerly IRT Perundurai Medical College)",
  "Government Dharmapuri Medical College, Dharmapuri",
  "Faculty of Medicine , Sri Lalithambigai Medical College and Hospital",
  "E.S.I.C. Medical College & Hospital, K.K. Nagar, Chennai earlier known as ESIC Medical College & PGIMSR, K.K Nagar, Chennai",
  "Dhanalakshmi Srinivasan Medical College and Hospital,Perambalur",
  "Dhanalakshmi Srinivasan Institute of Medical Sciences and Hospital,",
  "Coimbatore Medical College, Coimbatore",
  "Christian Medical College, Vellore",
  "Chettinad Hospital & Research Institute, Kanchipuram",
  "Chengalpattu Medical College, Chengalpattu",
  "Bhaarat Medical College & Hospital",
  "Arunai Medical College And Hospital",
  "Annapoorna Medical College & Hospital, Salem",
  "Annaii Medical College and Hospital",
  "All India Institute of Medical Sciences, Madurai",
  "ACS Medical College and Hospital, Chennai",
  "TRR Institute of Medical Sciences, Patancheru",
  "S V S Medical College, Mehboobnagar",
  "Surabhi Institute of Medical Sciences, Siddipet, Telangana",
  "Shadan Institute of Medical Sciences,Research Centre and Teaching Hospital, Peerancheru",
  "R.V.M. Institute of Medical Sciences and Research Centre, Siddipet",
  "Rajiv Gandhi Institute of Medical Sciences, adilabad",
  "Prathima Relief Institue of Medical Sciences",
  "Prathima Institute Of Medical Sciences, Karimnagar",
  "Osmania Medical College, Hyderabad",
  "Nova Institute of Medical Sciences and Research Centre",
  "Neelima Institute of Medical Sciences, Medchal",
  "MNR Medical College & Hospital, Sangareddy",
  "Mediciti Institute Of Medical Sciences, Ghanpur",
  "Mamata Medical College, Khammam",
  "Mamata Academy of Medical Sciences, Bachupally",
  "Mallareddy Medical College for Women, Hyderabad",
  "Malla Reddy Institute of Medical Sciences, Hyderabad",
  "Maheshwara Medical College, Chitkul, Patancheru, Medak",
  "Mahavir Institute of Medical Sciences, Vikarabad, Telengana",
  "Kamineni Institute of Medical Sciences, Narketpally",
  "Kamineni Academy of Medical Sciences & Research Center, Hyderabad",
  "Kakatiya Medical College, Warangal",
  "Government Medical College, Yadadri",
  "Government Medical College, Wanaparthy",
  "Government Medical College, Vikarabad",
  "Government Medical College, Suryapet",
  "Government Medical College, Siddipet",
  "Government Medical College, Sangareddy",
  "Government Medical College, Ramagundam",
  "Government Medical College, Rajanna Sircilla",
  "Government medical College, Quthbullapur",
  "Government Medical College, Nizamabad",
  "Government Medical College, Nirmal",
  "Government Medical College, Narsampet",
  "Government Medical College, Narayanpet",
  "Government Medical College, Nalgonda",
  "Government Medical College, Nagarkurnool",
  "Government Medical College, Mulugu",
  "Government Medical College, Medak",
  "Government Medical College, Mancherial",
  "Government Medical College, Maheshwaram",
  "Government Medical College, Mahabubnagar",
  "Government Medical College, Mahabubabad",
  "Government Medical College, Kumuram Bheem Asifabad",
  "Government Medical College, Khammam",
  "Government Medical College, Karimnagar",
  "Government Medical College, Kamareddy",
  "Government Medical College, Jogulamba",
  "Government Medical College, Jayashankar Bhupalpally",
  "Government Medical College Jangaon",
  "Government Medical College, Jagtial",
  "Government Medical College, Bhadradri Kothagudem",
  "Gandhi Medical College, Secunderabad",
  "Father Colombo Institute of Medical Sciences",
  "Employees State Insurance Coporation Medical College, Sanath Nagar, Hyderabad",
  "Dr. VRK Womens Medical College, Aziznagar",
  "Dr. Patnam Mahender Reddy Institute of Medical Sciences, Chevella, Rangareddy",
  "Deccan College of Medical Sciences, Hyderabad",
  "CMR Institute of Medical Sciences",
  "Chalmeda Anand Rao Insttitute Of Medical Sciences, Karimnagar",
  "Bhaskar Medical College, Yenkapally",
  "Ayaan Institute of Medical Sciences, Teaching Hospital & Research Centre, Kanaka Mamidi, R.R. Dist",
  "Arundathi Institute of Medical Sciences",
  "Apollo Institute of Medical Sciences and Research, Hyderabad",
  "All India Institute of Medical Sciences, Bibinagar",
  "Tripura Santiniketan Medical College & Hospital",
  "Tripura Medical College and Dr. B R A M Teaching Hospital, Agartala",
  "Agartala Government Medical College,Agartala",
];